### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by darren-reddick**
This PR is to add a Github actions workflow to take advantage of the features offered by Github Actions and more closely integrate the code and CI.

This replicates all of the steps performed by Travis, some improvements could later be made if using Github Actions is accepted. 
The Slack notification hasnt been included in the GH actions workflow as it probably isnt required at the moment as we are still using Travis in parallel.

### CODE REVIEW

**Review by cewood — APPROVED** [review]
LGTM :+1:

**Review by Ottovsky — APPROVED** [review]
lgtm

**Comment by Ottovsky** [comment]
Would it be worth to trigger tests on pull request as well ?

**Comment by cewood** [comment]
> Would it be worth to trigger tests on pull request as well ?

Absolutely, ignore my last... I clearly didn't look hard enough :see_no_evil: 

I'd make only the `Push to Docker Hub` conditional, all other steps should run on any push or pull, regardless of branch or fork, etc

**Comment by darren-reddick** [comment]
> Would it be worth to trigger tests on pull request as well ?

Yes - good point. I'll update this...

**Comment by darren-reddick** [comment]
The other thing i was thinking was that maybe we suppress the dockerhub push steps in Github Actions for the moment. Do we want both Travis and GH Actions publishing to dockerhub?

**Comment by Ottovsky** [comment]
Travis CI/CD is broken so it won't be pushing to docker hub. I would leave github actions to do the push, the layers should be the same in the docker registry, so it won't take any additional space and only tagging can be different.

**Comment by darren-reddick** [comment]
> Travis CI/CD is broken so it won't be pushing to docker hub. I would leave github actions to do the push, the layers should be the same for travis and github builds in the docker registry, so it won't take any additional space and possibly only tags will be different (imo, not real issue).

Of course - i forgot about the creds being broken in Travis. I will leave the push to dockerhub in.

**Review by Ottovsky — APPROVED** [review]
looks good now

**Pull request merged**
