### PR TITLE
modified customer-orders.html to support full URLs and modified basket.html

### PR DESCRIPTION
**Pull request by rberlind**
I modified customer-orders.html to support full URLs and modified basket.html to avoid extra order and to hide Change buttons when address and payment already populated.

The first change is in connection with https://github.com/microservices-demo/front-end/issues/84 which explains that when running on Apcera, I am using fully qualified DNS names and using ports different from 80.  I therefore need selfRef.replace("http://orders", "") to replace more than "http://orders" which is what my proposed change to `selfRef.replace(/http:\/\/(.*)\/orders/, "/orders")` does.  Note that "/" is escaped where needed.

The changes to basket.html relate to functional issues I reported in https://github.com/microservices-demo/front-end/issues/85 and https://github.com/microservices-demo/front-end/issues/86.  The changes for issue 85 are implemented with the orderPlaced variable which avoids the generation of an extra order just for the $4.99 shipping.  The changes for issue 86 are implemented in connection with the change_shipping and change_payment elements.  The idea here is to only make the newly relabeled "Add" buttons visible if the customer does not yet have a shipping address or a credit card associated with their account.  I find this desirable since clicking the buttons does not actually replace the original shipping address or credit card with new ones; instead, the new ones are simply added to the user-db database.  But since the front-end UI and user app never bring back any addresses or credit cards other than the first ones in the arrays, it seems to me better to only allow users to add them when they don't already have them.  That also hopefully explains the change in label from "Change" to "Add".

I attempted to run the various tests, but ultimately ran into an issue with make e2e which said it could not find bash.  Here is the output from make e2e:

Roger's-MacBook-Pro:front-end roger.berlind$ make e2e
Sending build context to Docker daemon 47.89 MB
Step 1/6 : FROM node:4-alpine
 ---> b04b0d965c67
Step 2/6 : RUN apk update && apk add make
 ---> Using cache
 ---> 0df7653f5b98
Step 3/6 : RUN npm install -g phantomjs-prebuilt
 ---> Using cache
 ---> 22b43b71d5da
Step 4/6 : RUN npm install -g casperjs
 ---> Using cache
 ---> e30bc54e093f
Step 5/6 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 1f66f4dd9558
Step 6/6 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 0dd30d5798ab
Successfully built 0dd30d5798ab
env: can't execute 'bash': No such file or directory
make: *** [e2e] Error 127

After doing my first commit that changed the labels on the buttons from "Change" to "Add", I went ahead and changed the corresponding variable/control names to use "add" instead of "change" to be more consistent and committed those changes to my fork.

### CODE REVIEW

**Comment by rberlind** [comment]
The Travis test seems to have failed based on not liking the version of node used.  But it seems to me that the test should be determining the version of node to use.  I did not specify any version.

**Comment by nustiueudinastea** [comment]
Hi @rberlind. Thanks for the PR. Could you please re-pull the latest code from master because I fixed a build error, which caused your PR to fail as well. This should fix it, and once the test passes I will merge your PR.

**Comment by rberlind** [comment]
Thanks @nustiueudinastea.  I will try that.
Roger

**Comment by rberlind** [comment]
OK.  That worked.  The test passed.  Thanks.

**Comment by rberlind** [comment]
Note that I also had failed tests for microservices-demo/queue-master.  If you or someone else could check that out, I would really appreciate it.

**Pull request merged**
